// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Dependency.proto

package dra

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UncoveredAddressKind int32

const (
	UncoveredAddressKind_Outside           UncoveredAddressKind = 0
	UncoveredAddressKind_InputRelated      UncoveredAddressKind = 1
	UncoveredAddressKind_DependencyRelated UncoveredAddressKind = 2
	UncoveredAddressKind_Other             UncoveredAddressKind = 3
)

var UncoveredAddressKind_name = map[int32]string{
	0: "Outside",
	1: "InputRelated",
	2: "DependencyRelated",
	3: "Other",
}

var UncoveredAddressKind_value = map[string]int32{
	"Outside":           0,
	"InputRelated":      1,
	"DependencyRelated": 2,
	"Other":             3,
}

func (x UncoveredAddressKind) String() string {
	return proto.EnumName(UncoveredAddressKind_name, int32(x))
}

func (UncoveredAddressKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{0}
}

type FileOperationsKind int32

const (
	FileOperationsKind_default        FileOperationsKind = 0
	FileOperationsKind_init           FileOperationsKind = 1
	FileOperationsKind_llseek         FileOperationsKind = 2
	FileOperationsKind_read           FileOperationsKind = 3
	FileOperationsKind_write          FileOperationsKind = 4
	FileOperationsKind_poll           FileOperationsKind = 9
	FileOperationsKind_unlocked_ioctl FileOperationsKind = 10
	FileOperationsKind_mmap           FileOperationsKind = 12
	FileOperationsKind_open           FileOperationsKind = 14
	FileOperationsKind_release        FileOperationsKind = 16
)

var FileOperationsKind_name = map[int32]string{
	0:  "default",
	1:  "init",
	2:  "llseek",
	3:  "read",
	4:  "write",
	9:  "poll",
	10: "unlocked_ioctl",
	12: "mmap",
	14: "open",
	16: "release",
}

var FileOperationsKind_value = map[string]int32{
	"default":        0,
	"init":           1,
	"llseek":         2,
	"read":           3,
	"write":          4,
	"poll":           9,
	"unlocked_ioctl": 10,
	"mmap":           12,
	"open":           14,
	"release":        16,
}

func (x FileOperationsKind) String() string {
	return proto.EnumName(FileOperationsKind_name, int32(x))
}

func (FileOperationsKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{1}
}

type WriteAddress struct {
	// the address writes to global variable
	WriteAddress uint32 `protobuf:"varint,2,opt,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty"`
	// the address of condition which is related to this global variable
	ConditionAddress uint32 `protobuf:"varint,3,opt,name=condition_address,json=conditionAddress,proto3" json:"condition_address,omitempty"`
	//    map<uint32, Input> write_input = 4;
	//    map<uint32, Syscall> write_syscall = 5;
	//    repeated Input write_input = 4;
	//    repeated Syscall write_syscall = 5;
	// 0 is undef
	// 1 is constant
	Kind uint32 `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// uncovered address,
	UncoveredAddress map[uint32]*WriteAddressAttributes `protobuf:"bytes,23,rep,name=uncovered_address,json=uncoveredAddress,proto3" json:"uncovered_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// file_operations name, file_operations_function index bits
	FileOperationsFunction map[string]uint32 `protobuf:"bytes,24,rep,name=file_operations_function,json=fileOperationsFunction,proto3" json:"file_operations_function,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// sig, index by bits
	Input map[string]uint32 `protobuf:"bytes,25,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// it is the data of uncovered address
	RunTimeDate          *RunTimeData `protobuf:"bytes,11,opt,name=run_time_date,json=runTimeDate,proto3" json:"run_time_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WriteAddress) Reset()         { *m = WriteAddress{} }
func (m *WriteAddress) String() string { return proto.CompactTextString(m) }
func (*WriteAddress) ProtoMessage()    {}
func (*WriteAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{0}
}

func (m *WriteAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteAddress.Unmarshal(m, b)
}
func (m *WriteAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteAddress.Marshal(b, m, deterministic)
}
func (m *WriteAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteAddress.Merge(m, src)
}
func (m *WriteAddress) XXX_Size() int {
	return xxx_messageInfo_WriteAddress.Size(m)
}
func (m *WriteAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteAddress.DiscardUnknown(m)
}

var xxx_messageInfo_WriteAddress proto.InternalMessageInfo

func (m *WriteAddress) GetWriteAddress() uint32 {
	if m != nil {
		return m.WriteAddress
	}
	return 0
}

func (m *WriteAddress) GetConditionAddress() uint32 {
	if m != nil {
		return m.ConditionAddress
	}
	return 0
}

func (m *WriteAddress) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *WriteAddress) GetUncoveredAddress() map[uint32]*WriteAddressAttributes {
	if m != nil {
		return m.UncoveredAddress
	}
	return nil
}

func (m *WriteAddress) GetFileOperationsFunction() map[string]uint32 {
	if m != nil {
		return m.FileOperationsFunction
	}
	return nil
}

func (m *WriteAddress) GetInput() map[string]uint32 {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *WriteAddress) GetRunTimeDate() *RunTimeData {
	if m != nil {
		return m.RunTimeDate
	}
	return nil
}

type WriteAddressAttributes struct {
	// the address writes to global variable
	WriteAddress         uint32   `protobuf:"varint,2,opt,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty"`
	Repeat               uint32   `protobuf:"varint,7,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Prio                 uint32   `protobuf:"varint,6,opt,name=prio,proto3" json:"prio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteAddressAttributes) Reset()         { *m = WriteAddressAttributes{} }
func (m *WriteAddressAttributes) String() string { return proto.CompactTextString(m) }
func (*WriteAddressAttributes) ProtoMessage()    {}
func (*WriteAddressAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{1}
}

func (m *WriteAddressAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteAddressAttributes.Unmarshal(m, b)
}
func (m *WriteAddressAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteAddressAttributes.Marshal(b, m, deterministic)
}
func (m *WriteAddressAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteAddressAttributes.Merge(m, src)
}
func (m *WriteAddressAttributes) XXX_Size() int {
	return xxx_messageInfo_WriteAddressAttributes.Size(m)
}
func (m *WriteAddressAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteAddressAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_WriteAddressAttributes proto.InternalMessageInfo

func (m *WriteAddressAttributes) GetWriteAddress() uint32 {
	if m != nil {
		return m.WriteAddress
	}
	return 0
}

func (m *WriteAddressAttributes) GetRepeat() uint32 {
	if m != nil {
		return m.Repeat
	}
	return 0
}

func (m *WriteAddressAttributes) GetPrio() uint32 {
	if m != nil {
		return m.Prio
	}
	return 0
}

type UncoveredAddress struct {
	ConditionAddress            uint32               `protobuf:"varint,1,opt,name=condition_address,json=conditionAddress,proto3" json:"condition_address,omitempty"`
	UncoveredAddress            uint32               `protobuf:"varint,2,opt,name=uncovered_address,json=uncoveredAddress,proto3" json:"uncovered_address,omitempty"`
	RightBranchAddress          []uint32             `protobuf:"varint,3,rep,packed,name=right_branch_address,json=rightBranchAddress,proto3" json:"right_branch_address,omitempty"`
	NumberArriveBasicblocks     uint32               `protobuf:"varint,4,opt,name=number_arrive_basicblocks,json=numberArriveBasicblocks,proto3" json:"number_arrive_basicblocks,omitempty"`
	Kind                        UncoveredAddressKind `protobuf:"varint,5,opt,name=kind,proto3,enum=dra.UncoveredAddressKind" json:"kind,omitempty"`
	NumberDominatorInstructions uint32               `protobuf:"varint,6,opt,name=number_dominator_instructions,json=numberDominatorInstructions,proto3" json:"number_dominator_instructions,omitempty"`
	// sig, index by bits
	Input                map[string]uint32                  `protobuf:"bytes,22,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	WriteAddress         map[uint32]*WriteAddressAttributes `protobuf:"bytes,23,rep,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Count                uint32                             `protobuf:"varint,24,opt,name=count,proto3" json:"count,omitempty"`
	RunTimeDate          *RunTimeData                       `protobuf:"bytes,8,opt,name=run_time_date,json=runTimeDate,proto3" json:"run_time_date,omitempty"`
	WriteAddressStatus   map[uint32]TaskStatus              `protobuf:"bytes,32,rep,name=write_address_status,json=writeAddressStatus,proto3" json:"write_address_status,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=dra.TaskStatus"`
	TasksCount           map[int32]uint32                   `protobuf:"bytes,33,rep,name=tasks_count,json=tasksCount,proto3" json:"tasks_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	WriteCount           map[int32]uint32                   `protobuf:"bytes,34,rep,name=write_count,json=writeCount,proto3" json:"write_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *UncoveredAddress) Reset()         { *m = UncoveredAddress{} }
func (m *UncoveredAddress) String() string { return proto.CompactTextString(m) }
func (*UncoveredAddress) ProtoMessage()    {}
func (*UncoveredAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{2}
}

func (m *UncoveredAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UncoveredAddress.Unmarshal(m, b)
}
func (m *UncoveredAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UncoveredAddress.Marshal(b, m, deterministic)
}
func (m *UncoveredAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UncoveredAddress.Merge(m, src)
}
func (m *UncoveredAddress) XXX_Size() int {
	return xxx_messageInfo_UncoveredAddress.Size(m)
}
func (m *UncoveredAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_UncoveredAddress.DiscardUnknown(m)
}

var xxx_messageInfo_UncoveredAddress proto.InternalMessageInfo

func (m *UncoveredAddress) GetConditionAddress() uint32 {
	if m != nil {
		return m.ConditionAddress
	}
	return 0
}

func (m *UncoveredAddress) GetUncoveredAddress() uint32 {
	if m != nil {
		return m.UncoveredAddress
	}
	return 0
}

func (m *UncoveredAddress) GetRightBranchAddress() []uint32 {
	if m != nil {
		return m.RightBranchAddress
	}
	return nil
}

func (m *UncoveredAddress) GetNumberArriveBasicblocks() uint32 {
	if m != nil {
		return m.NumberArriveBasicblocks
	}
	return 0
}

func (m *UncoveredAddress) GetKind() UncoveredAddressKind {
	if m != nil {
		return m.Kind
	}
	return UncoveredAddressKind_Outside
}

func (m *UncoveredAddress) GetNumberDominatorInstructions() uint32 {
	if m != nil {
		return m.NumberDominatorInstructions
	}
	return 0
}

func (m *UncoveredAddress) GetInput() map[string]uint32 {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *UncoveredAddress) GetWriteAddress() map[uint32]*WriteAddressAttributes {
	if m != nil {
		return m.WriteAddress
	}
	return nil
}

func (m *UncoveredAddress) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UncoveredAddress) GetRunTimeDate() *RunTimeData {
	if m != nil {
		return m.RunTimeDate
	}
	return nil
}

func (m *UncoveredAddress) GetWriteAddressStatus() map[uint32]TaskStatus {
	if m != nil {
		return m.WriteAddressStatus
	}
	return nil
}

func (m *UncoveredAddress) GetTasksCount() map[int32]uint32 {
	if m != nil {
		return m.TasksCount
	}
	return nil
}

func (m *UncoveredAddress) GetWriteCount() map[int32]uint32 {
	if m != nil {
		return m.WriteCount
	}
	return nil
}

type Dependency struct {
	Input                *Input            `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	UncoveredAddress     *UncoveredAddress `protobuf:"bytes,2,opt,name=uncovered_address,json=uncoveredAddress,proto3" json:"uncovered_address,omitempty"`
	WriteAddress         []*WriteAddress   `protobuf:"bytes,3,rep,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{3}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Dependency) GetUncoveredAddress() *UncoveredAddress {
	if m != nil {
		return m.UncoveredAddress
	}
	return nil
}

func (m *Dependency) GetWriteAddress() []*WriteAddress {
	if m != nil {
		return m.WriteAddress
	}
	return nil
}

type FileOperationsFunction struct {
	Name               string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileOperationsName string             `protobuf:"bytes,2,opt,name=file_operations_name,json=fileOperationsName,proto3" json:"file_operations_name,omitempty"`
	Kind               FileOperationsKind `protobuf:"varint,3,opt,name=kind,proto3,enum=dra.FileOperationsKind" json:"kind,omitempty"`
	Cmd                uint64             `protobuf:"varint,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	//    repeated Condition critical_condition = 4;
	//    map<uint32, Condition> critical_condition = 4;
	// it is the data of this syscall
	RunTimeDate *RunTimeData `protobuf:"bytes,5,opt,name=run_time_date,json=runTimeDate,proto3" json:"run_time_date,omitempty"`
	//    repeated WriteAddress write_address = 11;
	WriteAddress         map[uint32]uint32 `protobuf:"bytes,11,rep,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FileOperationsFunction) Reset()         { *m = FileOperationsFunction{} }
func (m *FileOperationsFunction) String() string { return proto.CompactTextString(m) }
func (*FileOperationsFunction) ProtoMessage()    {}
func (*FileOperationsFunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{4}
}

func (m *FileOperationsFunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileOperationsFunction.Unmarshal(m, b)
}
func (m *FileOperationsFunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileOperationsFunction.Marshal(b, m, deterministic)
}
func (m *FileOperationsFunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileOperationsFunction.Merge(m, src)
}
func (m *FileOperationsFunction) XXX_Size() int {
	return xxx_messageInfo_FileOperationsFunction.Size(m)
}
func (m *FileOperationsFunction) XXX_DiscardUnknown() {
	xxx_messageInfo_FileOperationsFunction.DiscardUnknown(m)
}

var xxx_messageInfo_FileOperationsFunction proto.InternalMessageInfo

func (m *FileOperationsFunction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileOperationsFunction) GetFileOperationsName() string {
	if m != nil {
		return m.FileOperationsName
	}
	return ""
}

func (m *FileOperationsFunction) GetKind() FileOperationsKind {
	if m != nil {
		return m.Kind
	}
	return FileOperationsKind_default
}

func (m *FileOperationsFunction) GetCmd() uint64 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *FileOperationsFunction) GetRunTimeDate() *RunTimeData {
	if m != nil {
		return m.RunTimeDate
	}
	return nil
}

func (m *FileOperationsFunction) GetWriteAddress() map[uint32]uint32 {
	if m != nil {
		return m.WriteAddress
	}
	return nil
}

type FileOperations struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//cmd or 0, function
	FileOperationsFunction map[int64]*FileOperationsFunction `protobuf:"bytes,3,rep,name=file_operations_function,json=fileOperationsFunction,proto3" json:"file_operations_function,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}                          `json:"-"`
	XXX_unrecognized       []byte                            `json:"-"`
	XXX_sizecache          int32                             `json:"-"`
}

func (m *FileOperations) Reset()         { *m = FileOperations{} }
func (m *FileOperations) String() string { return proto.CompactTextString(m) }
func (*FileOperations) ProtoMessage()    {}
func (*FileOperations) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{5}
}

func (m *FileOperations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileOperations.Unmarshal(m, b)
}
func (m *FileOperations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileOperations.Marshal(b, m, deterministic)
}
func (m *FileOperations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileOperations.Merge(m, src)
}
func (m *FileOperations) XXX_Size() int {
	return xxx_messageInfo_FileOperations.Size(m)
}
func (m *FileOperations) XXX_DiscardUnknown() {
	xxx_messageInfo_FileOperations.DiscardUnknown(m)
}

var xxx_messageInfo_FileOperations proto.InternalMessageInfo

func (m *FileOperations) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileOperations) GetFileOperationsFunction() map[int64]*FileOperationsFunction {
	if m != nil {
		return m.FileOperationsFunction
	}
	return nil
}

type Address struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 map[string]string `protobuf:"bytes,2,rep,name=addr,proto3" json:"addr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{6}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetAddr() map[string]string {
	if m != nil {
		return m.Addr
	}
	return nil
}

type Condition struct {
	ConditionAddress          uint64 `protobuf:"varint,1,opt,name=condition_address,json=conditionAddress,proto3" json:"condition_address,omitempty"`
	SyzkallerConditionAddress uint32 `protobuf:"varint,2,opt,name=syzkaller_condition_address,json=syzkallerConditionAddress,proto3" json:"syzkaller_condition_address,omitempty"`
	UncoveredAddress          uint64 `protobuf:"varint,3,opt,name=uncovered_address,json=uncoveredAddress,proto3" json:"uncovered_address,omitempty"`
	SyzkallerUncoveredAddress uint32 `protobuf:"varint,4,opt,name=syzkaller_uncovered_address,json=syzkallerUncoveredAddress,proto3" json:"syzkaller_uncovered_address,omitempty"`
	Idx                       uint32 `protobuf:"varint,5,opt,name=idx,proto3" json:"idx,omitempty"`
	Successor                 uint64 `protobuf:"varint,6,opt,name=successor,proto3" json:"successor,omitempty"`
	//    map<uint64, uint32> right_branch_address = 7;
	//    map<uint32, uint32> syzkaller_right_branch_address = 8;
	//    map<uint64, uint32> wrong_branch_address = 9;
	//    map<uint32, uint32> syzkaller_wrong_branch_address = 10;
	RightBranchAddress          []uint64 `protobuf:"varint,7,rep,packed,name=right_branch_address,json=rightBranchAddress,proto3" json:"right_branch_address,omitempty"`
	SyzkallerRightBranchAddress []uint32 `protobuf:"varint,8,rep,packed,name=syzkaller_right_branch_address,json=syzkallerRightBranchAddress,proto3" json:"syzkaller_right_branch_address,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{7}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetConditionAddress() uint64 {
	if m != nil {
		return m.ConditionAddress
	}
	return 0
}

func (m *Condition) GetSyzkallerConditionAddress() uint32 {
	if m != nil {
		return m.SyzkallerConditionAddress
	}
	return 0
}

func (m *Condition) GetUncoveredAddress() uint64 {
	if m != nil {
		return m.UncoveredAddress
	}
	return 0
}

func (m *Condition) GetSyzkallerUncoveredAddress() uint32 {
	if m != nil {
		return m.SyzkallerUncoveredAddress
	}
	return 0
}

func (m *Condition) GetIdx() uint32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *Condition) GetSuccessor() uint64 {
	if m != nil {
		return m.Successor
	}
	return 0
}

func (m *Condition) GetRightBranchAddress() []uint64 {
	if m != nil {
		return m.RightBranchAddress
	}
	return nil
}

func (m *Condition) GetSyzkallerRightBranchAddress() []uint32 {
	if m != nil {
		return m.SyzkallerRightBranchAddress
	}
	return nil
}

type Conditions struct {
	//    map<uint64, Condition> condition = 10;
	Condition            []*Condition `protobuf:"bytes,10,rep,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Conditions) Reset()         { *m = Conditions{} }
func (m *Conditions) String() string { return proto.CompactTextString(m) }
func (*Conditions) ProtoMessage()    {}
func (*Conditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{8}
}

func (m *Conditions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conditions.Unmarshal(m, b)
}
func (m *Conditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conditions.Marshal(b, m, deterministic)
}
func (m *Conditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conditions.Merge(m, src)
}
func (m *Conditions) XXX_Size() int {
	return xxx_messageInfo_Conditions.Size(m)
}
func (m *Conditions) XXX_DiscardUnknown() {
	xxx_messageInfo_Conditions.DiscardUnknown(m)
}

var xxx_messageInfo_Conditions proto.InternalMessageInfo

func (m *Conditions) GetCondition() []*Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type WriteAddresses struct {
	Condition *Condition `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	//    map<uint32, WriteAddress> write_address = 4;
	WriteAddress         []*WriteAddress `protobuf:"bytes,4,rep,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WriteAddresses) Reset()         { *m = WriteAddresses{} }
func (m *WriteAddresses) String() string { return proto.CompactTextString(m) }
func (*WriteAddresses) ProtoMessage()    {}
func (*WriteAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef53ed4df45ea5a, []int{9}
}

func (m *WriteAddresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteAddresses.Unmarshal(m, b)
}
func (m *WriteAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteAddresses.Marshal(b, m, deterministic)
}
func (m *WriteAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteAddresses.Merge(m, src)
}
func (m *WriteAddresses) XXX_Size() int {
	return xxx_messageInfo_WriteAddresses.Size(m)
}
func (m *WriteAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_WriteAddresses proto.InternalMessageInfo

func (m *WriteAddresses) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *WriteAddresses) GetWriteAddress() []*WriteAddress {
	if m != nil {
		return m.WriteAddress
	}
	return nil
}

func init() {
	proto.RegisterEnum("dra.UncoveredAddressKind", UncoveredAddressKind_name, UncoveredAddressKind_value)
	proto.RegisterEnum("dra.FileOperationsKind", FileOperationsKind_name, FileOperationsKind_value)
	proto.RegisterType((*WriteAddress)(nil), "dra.WriteAddress")
	proto.RegisterMapType((map[string]uint32)(nil), "dra.WriteAddress.FileOperationsFunctionEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "dra.WriteAddress.InputEntry")
	proto.RegisterMapType((map[uint32]*WriteAddressAttributes)(nil), "dra.WriteAddress.UncoveredAddressEntry")
	proto.RegisterType((*WriteAddressAttributes)(nil), "dra.writeAddressAttributes")
	proto.RegisterType((*UncoveredAddress)(nil), "dra.UncoveredAddress")
	proto.RegisterMapType((map[string]uint32)(nil), "dra.UncoveredAddress.InputEntry")
	proto.RegisterMapType((map[int32]uint32)(nil), "dra.UncoveredAddress.TasksCountEntry")
	proto.RegisterMapType((map[uint32]*WriteAddressAttributes)(nil), "dra.UncoveredAddress.WriteAddressEntry")
	proto.RegisterMapType((map[uint32]TaskStatus)(nil), "dra.UncoveredAddress.WriteAddressStatusEntry")
	proto.RegisterMapType((map[int32]uint32)(nil), "dra.UncoveredAddress.WriteCountEntry")
	proto.RegisterType((*Dependency)(nil), "dra.Dependency")
	proto.RegisterType((*FileOperationsFunction)(nil), "dra.FileOperationsFunction")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.FileOperationsFunction.WriteAddressEntry")
	proto.RegisterType((*FileOperations)(nil), "dra.FileOperations")
	proto.RegisterMapType((map[int64]*FileOperationsFunction)(nil), "dra.FileOperations.FileOperationsFunctionEntry")
	proto.RegisterType((*Address)(nil), "dra.address")
	proto.RegisterMapType((map[string]string)(nil), "dra.address.AddrEntry")
	proto.RegisterType((*Condition)(nil), "dra.Condition")
	proto.RegisterType((*Conditions)(nil), "dra.Conditions")
	proto.RegisterType((*WriteAddresses)(nil), "dra.WriteAddresses")
}

func init() { proto.RegisterFile("Dependency.proto", fileDescriptor_4ef53ed4df45ea5a) }

var fileDescriptor_4ef53ed4df45ea5a = []byte{
	// 1163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0xc7, 0x49, 0xdb, 0x4c, 0x9a, 0x74, 0xbb, 0x6a, 0x53, 0x37, 0x3d, 0x50, 0x08, 0x3a,
	0x11, 0xf5, 0xb8, 0x02, 0x01, 0x1d, 0xa7, 0x4a, 0x07, 0xea, 0x1f, 0x2a, 0x55, 0x20, 0x2a, 0x85,
	0xc2, 0xbd, 0x20, 0x99, 0x8d, 0xbd, 0xbd, 0xae, 0xe2, 0xd8, 0xd1, 0xee, 0xba, 0xa5, 0x3c, 0x22,
	0x1e, 0xe1, 0x8b, 0xf0, 0xd1, 0xf8, 0x02, 0xbc, 0x21, 0xb4, 0xbb, 0x49, 0xec, 0xd8, 0x4e, 0x9b,
	0x3b, 0xdd, 0xdb, 0x7a, 0x77, 0xe6, 0x37, 0x7f, 0x76, 0x7e, 0xb3, 0x63, 0x40, 0xa7, 0x74, 0x4c,
	0x43, 0x9f, 0x86, 0xde, 0xdd, 0xc1, 0x98, 0x47, 0x32, 0xc2, 0xb6, 0xcf, 0x49, 0xab, 0x76, 0x1e,
	0x8e, 0x63, 0x69, 0x76, 0x5a, 0x70, 0x49, 0xc4, 0xd0, 0xac, 0x3b, 0x7f, 0x54, 0x60, 0xfd, 0x15,
	0x67, 0x92, 0x1e, 0xf9, 0x3e, 0xa7, 0x42, 0xe0, 0x0f, 0xa1, 0x7e, 0xab, 0xbe, 0x5d, 0x62, 0x36,
	0x9c, 0x52, 0xdb, 0xea, 0xd6, 0xfb, 0xeb, 0xb7, 0x69, 0xa1, 0xa7, 0xb0, 0xe9, 0x45, 0xa1, 0xcf,
	0x24, 0x8b, 0xc2, 0x99, 0xa0, 0xad, 0x05, 0xd1, 0xec, 0x60, 0x2a, 0x8c, 0xa1, 0x3c, 0x64, 0xa1,
	0xef, 0x94, 0xf5, 0xb9, 0x5e, 0xe3, 0x4b, 0xd8, 0x8c, 0x43, 0x2f, 0xba, 0xa1, 0x9c, 0xfa, 0x33,
	0x80, 0x9d, 0xb6, 0xdd, 0xad, 0xf5, 0x3e, 0x3a, 0xf0, 0x39, 0x39, 0x48, 0xfb, 0x74, 0xf0, 0xe3,
	0x54, 0x74, 0xb2, 0xf1, 0x4d, 0x28, 0xf9, 0x5d, 0x1f, 0xc5, 0x99, 0x6d, 0xfc, 0x1a, 0x9c, 0x2b,
	0x16, 0x50, 0x37, 0x1a, 0x53, 0x4e, 0x94, 0x0b, 0xc2, 0xbd, 0x8a, 0x43, 0x4f, 0xad, 0x1c, 0x47,
	0x83, 0x3f, 0xcb, 0x83, 0x9f, 0xb1, 0x80, 0x5e, 0xcc, 0x14, 0xce, 0x26, 0xf2, 0xc6, 0x44, 0xf3,
	0xaa, 0xf0, 0x10, 0xf7, 0xa0, 0xc2, 0x54, 0x42, 0x9d, 0x5d, 0x8d, 0xfa, 0x38, 0x8f, 0xaa, 0xf3,
	0x6d, 0x40, 0x8c, 0x28, 0xfe, 0x02, 0xea, 0x3c, 0x0e, 0x5d, 0xc9, 0x46, 0xd4, 0xf5, 0x89, 0xa4,
	0x4e, 0xad, 0x6d, 0x75, 0x6b, 0x3d, 0xa4, 0x75, 0x79, 0x1c, 0x5e, 0xb2, 0x11, 0x3d, 0x25, 0x92,
	0xf4, 0x6b, 0xc9, 0x07, 0x6d, 0xfd, 0x02, 0xdb, 0x85, 0xd1, 0x63, 0x04, 0xf6, 0x90, 0xde, 0x39,
	0x96, 0x4e, 0xaa, 0x5a, 0xe2, 0xcf, 0xa0, 0x72, 0x43, 0x82, 0x98, 0xea, 0x1b, 0xab, 0xf5, 0xf6,
	0x34, 0x70, 0xfa, 0xda, 0x8e, 0xa4, 0xe4, 0x6c, 0x10, 0x4b, 0x2a, 0xfa, 0x46, 0xf2, 0xb0, 0xf4,
	0xc2, 0x6a, 0x9d, 0xc3, 0xde, 0x3d, 0x29, 0x48, 0xdb, 0xa9, 0x1a, 0x3b, 0x5b, 0x69, 0x3b, 0xf5,
	0x34, 0xd4, 0x0b, 0x80, 0x24, 0xee, 0x37, 0xd1, 0xec, 0x30, 0x68, 0x16, 0x7b, 0xba, 0x5c, 0x3d,
	0x36, 0x61, 0x85, 0xd3, 0x31, 0x25, 0xd2, 0x59, 0xd5, 0xa7, 0x93, 0x2f, 0x55, 0x7a, 0x63, 0xce,
	0x22, 0x67, 0xc5, 0x94, 0x9e, 0x5a, 0x77, 0xfe, 0x5b, 0x03, 0x94, 0x4d, 0x69, 0x71, 0x41, 0x5b,
	0x0b, 0x0a, 0xfa, 0x69, 0x51, 0xf1, 0x1a, 0xb7, 0xf2, 0x35, 0xf9, 0x29, 0x6c, 0x71, 0xf6, 0xfa,
	0x5a, 0xba, 0x03, 0x4e, 0x42, 0xef, 0x3a, 0xc5, 0x16, 0xbb, 0x5b, 0xef, 0x63, 0x7d, 0x76, 0xac,
	0x8f, 0xa6, 0x1a, 0x87, 0xb0, 0x1b, 0xc6, 0xa3, 0x01, 0xe5, 0x2e, 0xe1, 0x9c, 0xdd, 0x50, 0x77,
	0x40, 0x04, 0xf3, 0x06, 0x41, 0xe4, 0x0d, 0xc5, 0x84, 0x44, 0x3b, 0x46, 0xe0, 0x48, 0x9f, 0x1f,
	0x27, 0xc7, 0xf8, 0xd9, 0x84, 0x6b, 0x95, 0xb6, 0xd5, 0x6d, 0xf4, 0x76, 0x75, 0x09, 0x64, 0x83,
	0xfd, 0x96, 0x85, 0xfe, 0x84, 0x86, 0xc7, 0xf0, 0xde, 0xc4, 0x94, 0x1f, 0x8d, 0x58, 0x48, 0x64,
	0xc4, 0x5d, 0x16, 0x0a, 0xc9, 0x63, 0x5d, 0x01, 0x62, 0x92, 0xb8, 0x3d, 0x23, 0x74, 0x3a, 0x95,
	0x39, 0x4f, 0x89, 0xe0, 0xe7, 0x53, 0x2e, 0x34, 0x35, 0x17, 0xda, 0x85, 0x36, 0x0b, 0xf8, 0xf0,
	0x5d, 0xf6, 0x62, 0xd3, 0xf4, 0xcf, 0xe9, 0xa7, 0xc9, 0x65, 0x60, 0xe6, 0x2b, 0x60, 0x0b, 0x2a,
	0x5e, 0x14, 0x87, 0xd2, 0x71, 0x4c, 0x69, 0xe9, 0x8f, 0x3c, 0xe7, 0xd6, 0x96, 0xe0, 0x1c, 0x76,
	0x61, 0x6b, 0xce, 0x33, 0x57, 0x48, 0x22, 0x63, 0xe1, 0xb4, 0x53, 0x2d, 0xe4, 0x5e, 0x07, 0x7f,
	0xd0, 0xf2, 0xc6, 0x4d, 0x7c, 0x9b, 0x3b, 0xc0, 0x67, 0x50, 0x93, 0x44, 0x0c, 0x85, 0x6b, 0x5c,
	0xfe, 0x40, 0xe3, 0x3e, 0x29, 0xc6, 0x55, 0xbd, 0x5a, 0x9c, 0x28, 0x39, 0x83, 0x07, 0x72, 0xb6,
	0xa1, 0x70, 0x8c, 0xa3, 0x06, 0xa7, 0x73, 0x1f, 0x8e, 0xf6, 0x2f, 0x8d, 0x73, 0x3b, 0xdb, 0x78,
	0x7b, 0xde, 0xb6, 0x7e, 0x86, 0xcd, 0xdc, 0xcd, 0xbc, 0xbb, 0xd6, 0xf4, 0x13, 0xec, 0x2c, 0x48,
	0x6b, 0x81, 0x8d, 0x27, 0x69, 0x1b, 0x8d, 0xde, 0x86, 0xb6, 0xa1, 0x92, 0x65, 0xd4, 0xd2, 0xb8,
	0x2f, 0x61, 0x23, 0x93, 0xd6, 0x34, 0x5e, 0xe5, 0xa1, 0xa0, 0x5f, 0xc2, 0x46, 0x26, 0x9b, 0x6f,
	0xa2, 0xde, 0xf9, 0xdb, 0x02, 0x48, 0x5e, 0x69, 0xdc, 0x9e, 0xf2, 0xc7, 0xd2, 0xb9, 0x01, 0xed,
	0xb7, 0xbe, 0x8e, 0x29, 0x53, 0x8e, 0x17, 0xf5, 0x9b, 0x5a, 0x6f, 0xbb, 0xf0, 0xb2, 0x0b, 0xda,
	0xd0, 0xf3, 0x2c, 0xdb, 0x6c, 0x5d, 0x2c, 0x9b, 0xb9, 0x97, 0x6b, 0x9e, 0x57, 0x9d, 0x7f, 0x4a,
	0xd0, 0x2c, 0x7e, 0x1e, 0x54, 0x73, 0x0d, 0xc9, 0x88, 0x4e, 0x0a, 0x45, 0xaf, 0x55, 0xb7, 0xcb,
	0xbe, 0xc0, 0x5a, 0xa6, 0xa4, 0x65, 0xf0, 0xfc, 0x73, 0xfa, 0xbd, 0xd2, 0x98, 0x76, 0x2c, 0x3b,
	0xd5, 0xb1, 0xb2, 0x10, 0xc3, 0xa4, 0x63, 0x21, 0xb0, 0xbd, 0x91, 0x99, 0x25, 0xca, 0x7d, 0xb5,
	0xcc, 0x73, 0xbc, 0xb2, 0x0c, 0xc7, 0xfb, 0xd9, 0x7c, 0xd4, 0x52, 0xe4, 0x2e, 0x0e, 0xf8, 0xa1,
	0x1e, 0xd4, 0xfa, 0x7a, 0x39, 0x32, 0x2c, 0xae, 0x8c, 0x7f, 0x2d, 0x68, 0xcc, 0xdb, 0x2e, 0x4c,
	0x32, 0xbb, 0x67, 0xcc, 0x31, 0xd7, 0xfa, 0x49, 0x41, 0x18, 0x6f, 0x33, 0xe8, 0xb4, 0xae, 0x96,
	0x1e, 0x0e, 0xec, 0x7b, 0x98, 0x5e, 0x0c, 0x91, 0x8e, 0xfc, 0x77, 0x0b, 0x56, 0x49, 0x32, 0x2f,
	0xe6, 0x42, 0xde, 0x87, 0xb2, 0x3a, 0x76, 0x4a, 0x3a, 0xbc, 0xa6, 0x46, 0x9d, 0xc8, 0x1f, 0xa8,
	0x74, 0x9b, 0x28, 0xb4, 0x4c, 0xeb, 0x4b, 0xa8, 0xce, 0xb6, 0x1e, 0x6a, 0x66, 0xd5, 0xb4, 0x13,
	0x7f, 0xda, 0x50, 0x3d, 0x99, 0x3e, 0xf6, 0x8b, 0x47, 0x82, 0x72, 0xc1, 0x48, 0xf0, 0x15, 0xec,
	0x89, 0xbb, 0xdf, 0x86, 0x24, 0x08, 0x28, 0x77, 0xf3, 0x6a, 0xe6, 0xa6, 0x77, 0x67, 0x22, 0x27,
	0x4b, 0x8d, 0x14, 0xb6, 0x31, 0x96, 0xe3, 0xf2, 0x9c, 0xb1, 0xbc, 0x5a, 0x39, 0x63, 0x2c, 0x37,
	0xec, 0x20, 0xb0, 0x99, 0xff, 0xab, 0xe6, 0x49, 0xbd, 0xaf, 0x96, 0xf8, 0x31, 0x54, 0x45, 0xec,
	0x79, 0x54, 0x88, 0x88, 0xeb, 0x37, 0xbf, 0xdc, 0x4f, 0x36, 0x16, 0x8e, 0x30, 0xab, 0x6d, 0xbb,
	0x5b, 0x2e, 0x1c, 0x61, 0x4e, 0xe0, 0xfd, 0xc4, 0xc3, 0x42, 0xdd, 0x35, 0x3d, 0xfe, 0x24, 0x71,
	0xf4, 0x73, 0x20, 0x9d, 0x43, 0x80, 0x59, 0x9e, 0x04, 0xfe, 0x18, 0xaa, 0xb3, 0xbc, 0x3a, 0xa0,
	0xcb, 0xa0, 0xa1, 0xcb, 0x60, 0x26, 0xd3, 0x4f, 0x04, 0x3a, 0x37, 0xd0, 0x48, 0x53, 0x91, 0x66,
	0xf4, 0x4d, 0xab, 0x5d, 0xac, 0x9f, 0x6f, 0x97, 0xe5, 0xa5, 0xda, 0xe5, 0xfe, 0x2b, 0xd8, 0x2a,
	0x1a, 0xb7, 0x70, 0x0d, 0x56, 0x2f, 0x62, 0x29, 0x98, 0x4f, 0xd1, 0x23, 0x8c, 0x60, 0xdd, 0xf4,
	0x77, 0x1a, 0x10, 0x49, 0x7d, 0x64, 0xe1, 0x6d, 0xd8, 0x4c, 0x5e, 0x84, 0xe9, 0x76, 0x09, 0x57,
	0xa1, 0x72, 0x21, 0xaf, 0x29, 0x47, 0xf6, 0xfe, 0x5f, 0x56, 0xbe, 0xb3, 0x0e, 0x27, 0xc8, 0x3e,
	0xbd, 0x22, 0x71, 0x20, 0xd1, 0x23, 0xbc, 0x06, 0x65, 0x16, 0x32, 0x89, 0x2c, 0x0c, 0xb0, 0x12,
	0x04, 0x82, 0xd2, 0x21, 0x2a, 0xa9, 0x5d, 0x4e, 0x89, 0x8f, 0x6c, 0x05, 0xa8, 0xdd, 0x45, 0x65,
	0xb5, 0x39, 0x8e, 0x82, 0x00, 0x55, 0x31, 0x86, 0x46, 0x1c, 0xaa, 0xf1, 0x91, 0xfa, 0x2e, 0x8b,
	0x3c, 0x19, 0x20, 0x50, 0xa7, 0xa3, 0x11, 0x19, 0xa3, 0x75, 0xb5, 0x8a, 0xc6, 0x34, 0x44, 0x0d,
	0x65, 0x89, 0xd3, 0x80, 0x12, 0x41, 0x11, 0x1a, 0xac, 0xe8, 0xdf, 0xc7, 0xcf, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x54, 0x94, 0xf9, 0xc2, 0x70, 0x0e, 0x00, 0x00,
}
