// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Input.proto

package dra

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FuzzingStat int32

const (
	FuzzingStat_StatGenerate       FuzzingStat = 0
	FuzzingStat_StatFuzz           FuzzingStat = 1
	FuzzingStat_StatCandidate      FuzzingStat = 2
	FuzzingStat_StatTriage         FuzzingStat = 3
	FuzzingStat_StatMinimize       FuzzingStat = 4
	FuzzingStat_StatSmash          FuzzingStat = 5
	FuzzingStat_StatHint           FuzzingStat = 6
	FuzzingStat_StatSeed           FuzzingStat = 7
	FuzzingStat_StatDependency     FuzzingStat = 8
	FuzzingStat_StatDependencyBoot FuzzingStat = 9
	FuzzingStat_StatDefault        FuzzingStat = -1
)

var FuzzingStat_name = map[int32]string{
	0:  "StatGenerate",
	1:  "StatFuzz",
	2:  "StatCandidate",
	3:  "StatTriage",
	4:  "StatMinimize",
	5:  "StatSmash",
	6:  "StatHint",
	7:  "StatSeed",
	8:  "StatDependency",
	9:  "StatDependencyBoot",
	-1: "StatDefault",
}

var FuzzingStat_value = map[string]int32{
	"StatGenerate":       0,
	"StatFuzz":           1,
	"StatCandidate":      2,
	"StatTriage":         3,
	"StatMinimize":       4,
	"StatSmash":          5,
	"StatHint":           6,
	"StatSeed":           7,
	"StatDependency":     8,
	"StatDependencyBoot": 9,
	"StatDefault":        -1,
}

func (x FuzzingStat) String() string {
	return proto.EnumName(FuzzingStat_name, int32(x))
}

func (FuzzingStat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{0}
}

type Call struct {
	Idx                  uint32            `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Address              map[uint32]uint32 `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{0}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetIdx() uint32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *Call) GetAddress() map[uint32]uint32 {
	if m != nil {
		return m.Address
	}
	return nil
}

type Input struct {
	// for program
	Sig                        string           `protobuf:"bytes,11,opt,name=sig,proto3" json:"sig,omitempty"`
	Program                    []byte           `protobuf:"bytes,12,opt,name=program,proto3" json:"program,omitempty"`
	Call                       map[uint32]*Call `protobuf:"bytes,13,rep,name=call,proto3" json:"call,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stable                     uint32           `protobuf:"varint,14,opt,name=stable,proto3" json:"stable,omitempty"`
	Paths                      []*Paths         `protobuf:"bytes,16,rep,name=paths,proto3" json:"paths,omitempty"`
	NumberConditions           uint32           `protobuf:"varint,17,opt,name=number_conditions,json=numberConditions,proto3" json:"number_conditions,omitempty"`
	NumberConditionsDependency uint32           `protobuf:"varint,18,opt,name=number_conditions_dependency,json=numberConditionsDependency,proto3" json:"number_conditions_dependency,omitempty"`
	// for dependency
	Stat FuzzingStat `protobuf:"varint,21,opt,name=stat,proto3,enum=dra.FuzzingStat" json:"stat,omitempty"`
	// uncovered address, index by bits
	UncoveredAddress map[uint32]uint32 `protobuf:"bytes,22,rep,name=uncovered_address,json=uncoveredAddress,proto3" json:"uncovered_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// write address, index by bits
	WriteAddress         map[uint32]uint32 `protobuf:"bytes,25,rep,name=write_address,json=writeAddress,proto3" json:"write_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ProgramBeforeMini    []byte            `protobuf:"bytes,30,opt,name=program_before_mini,json=programBeforeMini,proto3" json:"program_before_mini,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{1}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *Input) GetProgram() []byte {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *Input) GetCall() map[uint32]*Call {
	if m != nil {
		return m.Call
	}
	return nil
}

func (m *Input) GetStable() uint32 {
	if m != nil {
		return m.Stable
	}
	return 0
}

func (m *Input) GetPaths() []*Paths {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *Input) GetNumberConditions() uint32 {
	if m != nil {
		return m.NumberConditions
	}
	return 0
}

func (m *Input) GetNumberConditionsDependency() uint32 {
	if m != nil {
		return m.NumberConditionsDependency
	}
	return 0
}

func (m *Input) GetStat() FuzzingStat {
	if m != nil {
		return m.Stat
	}
	return FuzzingStat_StatGenerate
}

func (m *Input) GetUncoveredAddress() map[uint32]uint32 {
	if m != nil {
		return m.UncoveredAddress
	}
	return nil
}

func (m *Input) GetWriteAddress() map[uint32]uint32 {
	if m != nil {
		return m.WriteAddress
	}
	return nil
}

func (m *Input) GetProgramBeforeMini() []byte {
	if m != nil {
		return m.ProgramBeforeMini
	}
	return nil
}

type Inputs struct {
	// map<string, Input> input = 1;
	Input                []*Input `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inputs) Reset()         { *m = Inputs{} }
func (m *Inputs) String() string { return proto.CompactTextString(m) }
func (*Inputs) ProtoMessage()    {}
func (*Inputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{2}
}

func (m *Inputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inputs.Unmarshal(m, b)
}
func (m *Inputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inputs.Marshal(b, m, deterministic)
}
func (m *Inputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inputs.Merge(m, src)
}
func (m *Inputs) XXX_Size() int {
	return xxx_messageInfo_Inputs.Size(m)
}
func (m *Inputs) XXX_DiscardUnknown() {
	xxx_messageInfo_Inputs.DiscardUnknown(m)
}

var xxx_messageInfo_Inputs proto.InternalMessageInfo

func (m *Inputs) GetInput() []*Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type Path struct {
	Address              []uint32 `protobuf:"varint,1,rep,packed,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{3}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetAddress() []uint32 {
	if m != nil {
		return m.Address
	}
	return nil
}

type Paths struct {
	Path                 map[uint32]*Path `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}
func (*Paths) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{4}
}

func (m *Paths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paths.Unmarshal(m, b)
}
func (m *Paths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paths.Marshal(b, m, deterministic)
}
func (m *Paths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paths.Merge(m, src)
}
func (m *Paths) XXX_Size() int {
	return xxx_messageInfo_Paths.Size(m)
}
func (m *Paths) XXX_DiscardUnknown() {
	xxx_messageInfo_Paths.DiscardUnknown(m)
}

var xxx_messageInfo_Paths proto.InternalMessageInfo

func (m *Paths) GetPath() map[uint32]*Path {
	if m != nil {
		return m.Path
	}
	return nil
}

type UnstableInput struct {
	Sig          string   `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	Program      []byte   `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	UnstablePath []*Paths `protobuf:"bytes,12,rep,name=unstable_path,json=unstablePath,proto3" json:"unstable_path,omitempty"`
	// address, index by bits
	Address              map[uint32]uint32 `protobuf:"bytes,13,rep,name=address,proto3" json:"address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UnstableInput) Reset()         { *m = UnstableInput{} }
func (m *UnstableInput) String() string { return proto.CompactTextString(m) }
func (*UnstableInput) ProtoMessage()    {}
func (*UnstableInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{5}
}

func (m *UnstableInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnstableInput.Unmarshal(m, b)
}
func (m *UnstableInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnstableInput.Marshal(b, m, deterministic)
}
func (m *UnstableInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnstableInput.Merge(m, src)
}
func (m *UnstableInput) XXX_Size() int {
	return xxx_messageInfo_UnstableInput.Size(m)
}
func (m *UnstableInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnstableInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnstableInput proto.InternalMessageInfo

func (m *UnstableInput) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *UnstableInput) GetProgram() []byte {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *UnstableInput) GetUnstablePath() []*Paths {
	if m != nil {
		return m.UnstablePath
	}
	return nil
}

func (m *UnstableInput) GetAddress() map[uint32]uint32 {
	if m != nil {
		return m.Address
	}
	return nil
}

type UnstableInputs struct {
	UnstableInput        map[string]*UnstableInput `protobuf:"bytes,1,rep,name=unstable_input,json=unstableInput,proto3" json:"unstable_input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UnstableInputs) Reset()         { *m = UnstableInputs{} }
func (m *UnstableInputs) String() string { return proto.CompactTextString(m) }
func (*UnstableInputs) ProtoMessage()    {}
func (*UnstableInputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4691306fcd7be97, []int{6}
}

func (m *UnstableInputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnstableInputs.Unmarshal(m, b)
}
func (m *UnstableInputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnstableInputs.Marshal(b, m, deterministic)
}
func (m *UnstableInputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnstableInputs.Merge(m, src)
}
func (m *UnstableInputs) XXX_Size() int {
	return xxx_messageInfo_UnstableInputs.Size(m)
}
func (m *UnstableInputs) XXX_DiscardUnknown() {
	xxx_messageInfo_UnstableInputs.DiscardUnknown(m)
}

var xxx_messageInfo_UnstableInputs proto.InternalMessageInfo

func (m *UnstableInputs) GetUnstableInput() map[string]*UnstableInput {
	if m != nil {
		return m.UnstableInput
	}
	return nil
}

func init() {
	proto.RegisterEnum("dra.FuzzingStat", FuzzingStat_name, FuzzingStat_value)
	proto.RegisterType((*Call)(nil), "dra.Call")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.Call.AddressEntry")
	proto.RegisterType((*Input)(nil), "dra.Input")
	proto.RegisterMapType((map[uint32]*Call)(nil), "dra.Input.CallEntry")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.Input.UncoveredAddressEntry")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.Input.WriteAddressEntry")
	proto.RegisterType((*Inputs)(nil), "dra.Inputs")
	proto.RegisterType((*Path)(nil), "dra.Path")
	proto.RegisterType((*Paths)(nil), "dra.Paths")
	proto.RegisterMapType((map[uint32]*Path)(nil), "dra.Paths.PathEntry")
	proto.RegisterType((*UnstableInput)(nil), "dra.UnstableInput")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.UnstableInput.AddressEntry")
	proto.RegisterType((*UnstableInputs)(nil), "dra.UnstableInputs")
	proto.RegisterMapType((map[string]*UnstableInput)(nil), "dra.UnstableInputs.UnstableInputEntry")
}

func init() { proto.RegisterFile("Input.proto", fileDescriptor_e4691306fcd7be97) }

var fileDescriptor_e4691306fcd7be97 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf9, 0x6d, 0x26, 0x76, 0xb4, 0x19, 0xda, 0x68, 0x89, 0x2a, 0x6a, 0x45, 0x08, 0x45,
	0x45, 0x0a, 0xa8, 0x5c, 0xa0, 0x1c, 0xa0, 0x09, 0xbf, 0x87, 0x4a, 0x28, 0x6d, 0x85, 0xc4, 0x25,
	0xda, 0xc4, 0xdb, 0x74, 0xd5, 0x64, 0x1d, 0xd9, 0xeb, 0x96, 0xf4, 0x01, 0x78, 0x23, 0x24, 0xde,
	0x83, 0x47, 0xe0, 0x41, 0x40, 0xbb, 0x8e, 0x5d, 0xbb, 0xe9, 0x81, 0x1e, 0xc8, 0x21, 0xd9, 0x99,
	0xf9, 0x76, 0xf6, 0x9b, 0x9d, 0x6f, 0x36, 0x50, 0xff, 0x24, 0x17, 0x91, 0xea, 0x2d, 0x02, 0x5f,
	0xf9, 0x58, 0xf4, 0x02, 0xd6, 0xf9, 0x6e, 0x41, 0x69, 0xc0, 0x66, 0x33, 0x24, 0x50, 0x14, 0xde,
	0x37, 0x6a, 0xb9, 0x56, 0xd7, 0x19, 0xea, 0x25, 0x3e, 0x83, 0x2a, 0xf3, 0xbc, 0x80, 0x87, 0x21,
	0x2d, 0xb8, 0xc5, 0x6e, 0x7d, 0xaf, 0xd5, 0xf3, 0x02, 0xd6, 0xd3, 0xe8, 0xde, 0x41, 0x1c, 0x78,
	0x27, 0x55, 0xb0, 0x1c, 0x26, 0xb0, 0xf6, 0x3e, 0xd8, 0xd9, 0x80, 0xce, 0x79, 0xce, 0x97, 0x49,
	0xce, 0x73, 0xbe, 0xc4, 0x4d, 0x28, 0x5f, 0xb0, 0x59, 0xc4, 0x69, 0xc1, 0xf8, 0x62, 0x63, 0xbf,
	0xf0, 0xc2, 0xea, 0xfc, 0x2c, 0x43, 0xd9, 0xb0, 0xd3, 0xbb, 0x42, 0x31, 0xa5, 0x75, 0xd7, 0xea,
	0xd6, 0x86, 0x7a, 0x89, 0x14, 0xaa, 0x8b, 0xc0, 0x9f, 0x06, 0x6c, 0x4e, 0x6d, 0xd7, 0xea, 0xda,
	0xc3, 0xc4, 0xc4, 0x2e, 0x94, 0x26, 0x6c, 0x36, 0xa3, 0x8e, 0x21, 0xb8, 0x69, 0x08, 0xc6, 0x35,
	0x6a, 0x9a, 0x31, 0x3d, 0x83, 0xc0, 0x16, 0x54, 0x42, 0xc5, 0xc6, 0x33, 0x4e, 0x1b, 0xe6, 0xe8,
	0x95, 0x85, 0x2e, 0x94, 0x17, 0x4c, 0x9d, 0x85, 0x94, 0x98, 0x14, 0x60, 0x52, 0x7c, 0xd6, 0x9e,
	0x61, 0x1c, 0xc0, 0x27, 0xd0, 0x94, 0xd1, 0x7c, 0xcc, 0x83, 0xd1, 0xc4, 0x97, 0x9e, 0x50, 0xc2,
	0x97, 0x21, 0x6d, 0x9a, 0x24, 0x24, 0x0e, 0x0c, 0x52, 0x3f, 0xbe, 0x81, 0xed, 0x35, 0xf0, 0xc8,
	0xe3, 0x0b, 0x2e, 0x3d, 0x2e, 0x27, 0x4b, 0x8a, 0x66, 0x5f, 0xfb, 0xe6, 0xbe, 0xb7, 0x29, 0x02,
	0x1f, 0x41, 0x29, 0x54, 0x4c, 0xd1, 0x2d, 0xd7, 0xea, 0x36, 0xf6, 0x88, 0xe1, 0xf3, 0x3e, 0xba,
	0xba, 0x12, 0x72, 0x7a, 0xa4, 0x98, 0x1a, 0x9a, 0x28, 0x1e, 0x42, 0x33, 0x92, 0x13, 0xff, 0x82,
	0x07, 0xdc, 0x1b, 0x25, 0x6d, 0x6a, 0x99, 0x12, 0xdc, 0xcc, 0x2d, 0x9c, 0x24, 0x98, 0x5c, 0xc3,
	0x48, 0x74, 0xc3, 0x8d, 0x07, 0xe0, 0x5c, 0x06, 0x42, 0xf1, 0x34, 0xd5, 0x03, 0x93, 0x6a, 0x3b,
	0x93, 0xea, 0x8b, 0x8e, 0xe7, 0xd2, 0xd8, 0x97, 0x19, 0x17, 0xf6, 0xe0, 0xfe, 0xaa, 0x2b, 0xa3,
	0x31, 0x3f, 0xf5, 0x03, 0x3e, 0x9a, 0x0b, 0x29, 0xe8, 0x43, 0xd3, 0xb0, 0xe6, 0x2a, 0xd4, 0x37,
	0x91, 0x43, 0x21, 0x45, 0xbb, 0x0f, 0xb5, 0xb4, 0x47, 0xb7, 0x28, 0x65, 0x27, 0xab, 0x94, 0xfa,
	0x5e, 0x2d, 0xd5, 0x5e, 0x46, 0x34, 0xed, 0x01, 0x6c, 0xdd, 0x5a, 0xe1, 0x5d, 0x94, 0xd7, 0x7e,
	0x0d, 0xcd, 0xb5, 0xda, 0xee, 0x24, 0xdd, 0x5d, 0xa8, 0x98, 0x2b, 0x0a, 0xb5, 0x98, 0x84, 0x5e,
	0x51, 0x2b, 0x23, 0x26, 0x13, 0x1b, 0xc6, 0x81, 0x8e, 0x0b, 0x25, 0x2d, 0x2e, 0x2d, 0xe9, 0xe4,
	0xaa, 0x35, 0xd6, 0x49, 0x87, 0xa8, 0x13, 0x41, 0xd9, 0xc8, 0x4f, 0x6b, 0x5b, 0x0b, 0x70, 0x95,
	0x6b, 0xf3, 0x5a, 0x98, 0xe6, 0x7b, 0xa5, 0x6d, 0x8d, 0xd0, 0x57, 0x99, 0xba, 0xfe, 0xf5, 0x2a,
	0xf5, 0x86, 0x6c, 0x11, 0xbf, 0x2d, 0x70, 0x4e, 0x64, 0x3c, 0x14, 0xb9, 0x39, 0xb4, 0x6e, 0x9d,
	0xc3, 0x42, 0x7e, 0x0e, 0x9f, 0x82, 0x13, 0xad, 0x36, 0x8f, 0x0c, 0x69, 0x7b, 0x6d, 0x9a, 0xec,
	0x04, 0x60, 0xea, 0x7f, 0x79, 0x5d, 0x7f, 0x3c, 0xbb, 0x3b, 0x06, 0x9a, 0x63, 0xf0, 0x1f, 0x5e,
	0x99, 0x1f, 0x16, 0x34, 0x72, 0x67, 0x84, 0x78, 0x08, 0x8d, 0x94, 0x7a, 0xb6, 0x79, 0x8f, 0xd7,
	0x09, 0x85, 0x79, 0x33, 0xe6, 0x95, 0x16, 0x6e, 0x7c, 0xed, 0x63, 0xc0, 0x75, 0x50, 0x96, 0x63,
	0x2d, 0xe6, 0xd8, 0xcd, 0x37, 0x05, 0xd7, 0x4f, 0xcb, 0xf0, 0xde, 0xfd, 0x65, 0x41, 0x3d, 0xf3,
	0x08, 0x20, 0x01, 0x5b, 0xff, 0x7e, 0xe0, 0x92, 0x07, 0x4c, 0x71, 0x72, 0x0f, 0x6d, 0xd8, 0xd0,
	0x1e, 0x0d, 0x22, 0x16, 0x36, 0xc1, 0xd1, 0xd6, 0x80, 0x49, 0x4f, 0x78, 0x1a, 0x50, 0xc0, 0x06,
	0x80, 0x76, 0x1d, 0x07, 0x82, 0x4d, 0x39, 0x29, 0x26, 0x29, 0xf4, 0x2c, 0xce, 0xc5, 0x15, 0x27,
	0x25, 0x74, 0xa0, 0xa6, 0x3d, 0x47, 0x73, 0x16, 0x9e, 0x91, 0x72, 0x92, 0xf1, 0xa3, 0x90, 0x8a,
	0x54, 0x12, 0xeb, 0x88, 0x73, 0x8f, 0x54, 0x11, 0xa1, 0xa1, 0xad, 0xeb, 0x67, 0x8b, 0x6c, 0x60,
	0x0b, 0x30, 0xef, 0xeb, 0xfb, 0xbe, 0x22, 0x35, 0xa4, 0x50, 0x8f, 0xfd, 0xa7, 0x2c, 0x9a, 0x29,
	0xf2, 0x27, 0xf9, 0x58, 0xfd, 0xea, 0xd7, 0x72, 0xef, 0x95, 0x17, 0xb0, 0x71, 0xc5, 0xfc, 0x23,
	0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x73, 0x06, 0xbe, 0xa0, 0x06, 0x00, 0x00,
}
