// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Statistic.proto

package dra

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Statistic struct {
	Name                 FuzzingStat `protobuf:"varint,1,opt,name=name,proto3,enum=dra.FuzzingStat" json:"name,omitempty"`
	ExecuteNum           uint64      `protobuf:"varint,11,opt,name=executeNum,proto3" json:"executeNum,omitempty"`
	Time                 float64     `protobuf:"fixed64,12,opt,name=time,proto3" json:"time,omitempty"`
	NewTestCaseNum       uint64      `protobuf:"varint,13,opt,name=newTestCaseNum,proto3" json:"newTestCaseNum,omitempty"`
	NewAddressNum        uint64      `protobuf:"varint,14,opt,name=newAddressNum,proto3" json:"newAddressNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Statistic) Reset()         { *m = Statistic{} }
func (m *Statistic) String() string { return proto.CompactTextString(m) }
func (*Statistic) ProtoMessage()    {}
func (*Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fb87f92dbb7b88, []int{0}
}

func (m *Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistic.Unmarshal(m, b)
}
func (m *Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistic.Marshal(b, m, deterministic)
}
func (m *Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistic.Merge(m, src)
}
func (m *Statistic) XXX_Size() int {
	return xxx_messageInfo_Statistic.Size(m)
}
func (m *Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_Statistic proto.InternalMessageInfo

func (m *Statistic) GetName() FuzzingStat {
	if m != nil {
		return m.Name
	}
	return FuzzingStat_StatDefault
}

func (m *Statistic) GetExecuteNum() uint64 {
	if m != nil {
		return m.ExecuteNum
	}
	return 0
}

func (m *Statistic) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Statistic) GetNewTestCaseNum() uint64 {
	if m != nil {
		return m.NewTestCaseNum
	}
	return 0
}

func (m *Statistic) GetNewAddressNum() uint64 {
	if m != nil {
		return m.NewAddressNum
	}
	return 0
}

type Time struct {
	Time                 float64  `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	ExecuteNum           int64    `protobuf:"varint,3,opt,name=executeNum,proto3" json:"executeNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fb87f92dbb7b88, []int{1}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Time) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Time) GetExecuteNum() int64 {
	if m != nil {
		return m.ExecuteNum
	}
	return 0
}

type Coverage struct {
	Coverage             map[uint32]uint32 `protobuf:"bytes,1,rep,name=coverage,proto3" json:"coverage,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Time                 []*Time           `protobuf:"bytes,2,rep,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Coverage) Reset()         { *m = Coverage{} }
func (m *Coverage) String() string { return proto.CompactTextString(m) }
func (*Coverage) ProtoMessage()    {}
func (*Coverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fb87f92dbb7b88, []int{2}
}

func (m *Coverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coverage.Unmarshal(m, b)
}
func (m *Coverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coverage.Marshal(b, m, deterministic)
}
func (m *Coverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coverage.Merge(m, src)
}
func (m *Coverage) XXX_Size() int {
	return xxx_messageInfo_Coverage.Size(m)
}
func (m *Coverage) XXX_DiscardUnknown() {
	xxx_messageInfo_Coverage.DiscardUnknown(m)
}

var xxx_messageInfo_Coverage proto.InternalMessageInfo

func (m *Coverage) GetCoverage() map[uint32]uint32 {
	if m != nil {
		return m.Coverage
	}
	return nil
}

func (m *Coverage) GetTime() []*Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type UsefulInput struct {
	Input                *Input   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Time                 float64  `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	Num                  uint64   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	NewAddress           []uint32 `protobuf:"varint,4,rep,packed,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsefulInput) Reset()         { *m = UsefulInput{} }
func (m *UsefulInput) String() string { return proto.CompactTextString(m) }
func (*UsefulInput) ProtoMessage()    {}
func (*UsefulInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fb87f92dbb7b88, []int{3}
}

func (m *UsefulInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsefulInput.Unmarshal(m, b)
}
func (m *UsefulInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsefulInput.Marshal(b, m, deterministic)
}
func (m *UsefulInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsefulInput.Merge(m, src)
}
func (m *UsefulInput) XXX_Size() int {
	return xxx_messageInfo_UsefulInput.Size(m)
}
func (m *UsefulInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UsefulInput.DiscardUnknown(m)
}

var xxx_messageInfo_UsefulInput proto.InternalMessageInfo

func (m *UsefulInput) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *UsefulInput) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *UsefulInput) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *UsefulInput) GetNewAddress() []uint32 {
	if m != nil {
		return m.NewAddress
	}
	return nil
}

type Statistics struct {
	SignalNum            uint64               `protobuf:"varint,1,opt,name=signalNum,proto3" json:"signalNum,omitempty"`
	BasicBlockNumber     uint32               `protobuf:"varint,10,opt,name=basic_block_number,json=basicBlockNumber,proto3" json:"basic_block_number,omitempty"`
	Coverage             *Coverage            `protobuf:"bytes,8,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Stat                 map[int32]*Statistic `protobuf:"bytes,11,rep,name=stat,proto3" json:"stat,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UsefulInput          []*UsefulInput       `protobuf:"bytes,12,rep,name=useful_input,json=usefulInput,proto3" json:"useful_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fb87f92dbb7b88, []int{4}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetSignalNum() uint64 {
	if m != nil {
		return m.SignalNum
	}
	return 0
}

func (m *Statistics) GetBasicBlockNumber() uint32 {
	if m != nil {
		return m.BasicBlockNumber
	}
	return 0
}

func (m *Statistics) GetCoverage() *Coverage {
	if m != nil {
		return m.Coverage
	}
	return nil
}

func (m *Statistics) GetStat() map[int32]*Statistic {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *Statistics) GetUsefulInput() []*UsefulInput {
	if m != nil {
		return m.UsefulInput
	}
	return nil
}

func init() {
	proto.RegisterType((*Statistic)(nil), "dra.Statistic")
	proto.RegisterType((*Time)(nil), "dra.Time")
	proto.RegisterType((*Coverage)(nil), "dra.Coverage")
	proto.RegisterMapType((map[uint32]uint32)(nil), "dra.Coverage.CoverageEntry")
	proto.RegisterType((*UsefulInput)(nil), "dra.UsefulInput")
	proto.RegisterType((*Statistics)(nil), "dra.Statistics")
	proto.RegisterMapType((map[int32]*Statistic)(nil), "dra.Statistics.StatEntry")
}

func init() { proto.RegisterFile("Statistic.proto", fileDescriptor_d8fb87f92dbb7b88) }

var fileDescriptor_d8fb87f92dbb7b88 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe5, 0x24, 0x45, 0xed, 0xb8, 0x29, 0x95, 0xc5, 0x21, 0x94, 0x7f, 0x51, 0x54, 0xa1,
	0x20, 0x41, 0x0f, 0xdd, 0x03, 0x08, 0x4e, 0xb0, 0x02, 0x84, 0x84, 0xf6, 0x60, 0x96, 0x73, 0xe5,
	0xa6, 0xa6, 0x8a, 0xb6, 0x71, 0x57, 0xb1, 0xdd, 0xb2, 0xfb, 0x32, 0xbc, 0x02, 0x12, 0x2f, 0x88,
	0x3c, 0xde, 0x4d, 0xdd, 0xdd, 0xdb, 0x78, 0xe6, 0x1b, 0xfb, 0xf3, 0x6f, 0x6c, 0x78, 0xf8, 0xc3,
	0x08, 0x53, 0x6b, 0x53, 0x57, 0xb3, 0xcb, 0x76, 0x6b, 0xb6, 0x2c, 0x5e, 0xb5, 0x62, 0x42, 0xbf,
	0xa9, 0x4b, 0x6b, 0x7c, 0xa6, 0xf8, 0x47, 0x60, 0xd0, 0xa9, 0xd8, 0x14, 0x12, 0x25, 0x1a, 0x99,
	0x91, 0x9c, 0x94, 0xa3, 0xf9, 0x78, 0xb6, 0x6a, 0xc5, 0xec, 0x8b, 0xbd, 0xbe, 0xae, 0xd5, 0xda,
	0x89, 0x38, 0x56, 0xd9, 0x73, 0x00, 0xf9, 0x5b, 0x56, 0xd6, 0xc8, 0x33, 0xdb, 0x64, 0x34, 0x27,
	0x65, 0xc2, 0x83, 0x0c, 0x63, 0x90, 0x98, 0xba, 0x91, 0xd9, 0x30, 0x27, 0x25, 0xe1, 0x18, 0xb3,
	0x97, 0x30, 0x52, 0x72, 0x7f, 0x2e, 0xb5, 0x39, 0x15, 0x1a, 0xfb, 0x52, 0xec, 0xbb, 0x93, 0x65,
	0x53, 0x48, 0x95, 0xdc, 0x7f, 0x5c, 0xad, 0x5a, 0xa9, 0xb5, 0x93, 0x8d, 0x50, 0x76, 0x9c, 0x2c,
	0xbe, 0x43, 0x72, 0xee, 0x76, 0xbd, 0x3d, 0x89, 0x04, 0x27, 0x8d, 0x21, 0x56, 0xb6, 0xc9, 0xa2,
	0x9c, 0x94, 0x31, 0x77, 0xe1, 0x1d, 0xbf, 0x31, 0x16, 0x82, 0x4c, 0xf1, 0x87, 0x40, 0xff, 0x74,
	0xbb, 0x93, 0xad, 0x58, 0x4b, 0xf6, 0x16, 0xfa, 0xd5, 0x4d, 0x9c, 0x91, 0x3c, 0x2e, 0xe9, 0xfc,
	0x09, 0x62, 0xb8, 0x15, 0x74, 0xc1, 0x67, 0x65, 0xda, 0x2b, 0xde, 0x89, 0xd9, 0xb3, 0x1b, 0x2f,
	0x11, 0x36, 0x0d, 0xb0, 0xc9, 0x99, 0xf4, 0xb6, 0x26, 0x1f, 0x20, 0x3d, 0xea, 0x74, 0x3e, 0x2f,
	0xe4, 0x15, 0x5a, 0x4f, 0xb9, 0x0b, 0xd9, 0x23, 0xe8, 0xed, 0xc4, 0xc6, 0x4a, 0xf4, 0x9e, 0x72,
	0xbf, 0x78, 0x1f, 0xbd, 0x23, 0xc5, 0x0e, 0xe8, 0x4f, 0x2d, 0x7f, 0xd9, 0x0d, 0x8e, 0x8e, 0xe5,
	0xd0, 0xab, 0x5d, 0x80, 0xcd, 0x74, 0x0e, 0x78, 0x16, 0x96, 0xb8, 0x2f, 0x74, 0x60, 0xa2, 0xfb,
	0x60, 0x62, 0x04, 0x8a, 0x60, 0x5e, 0x00, 0x55, 0x72, 0xbf, 0x10, 0x1e, 0x6c, 0x96, 0xe4, 0x71,
	0x99, 0x72, 0x38, 0xa0, 0x2e, 0xfe, 0x46, 0x00, 0xdd, 0xeb, 0xd0, 0xec, 0x29, 0x0c, 0x74, 0xbd,
	0x56, 0x62, 0xe3, 0x38, 0x12, 0xdc, 0xe7, 0x90, 0x60, 0xaf, 0x81, 0x2d, 0x85, 0xae, 0xab, 0xc5,
	0x72, 0xb3, 0xad, 0x2e, 0x16, 0xca, 0x36, 0x4b, 0xd9, 0x66, 0x80, 0x77, 0x19, 0x63, 0xe5, 0x93,
	0x2b, 0x9c, 0x61, 0x9e, 0xbd, 0x0a, 0x38, 0xf7, 0xf1, 0x1a, 0xe9, 0x11, 0xe7, 0x80, 0xec, 0x1b,
	0x48, 0xb4, 0x11, 0x26, 0xa3, 0x48, 0xf6, 0x31, 0xca, 0x0e, 0xae, 0x30, 0xf4, 0xc3, 0x40, 0x19,
	0x3b, 0x81, 0xa1, 0x45, 0x58, 0x0b, 0x0f, 0x69, 0x88, 0x6d, 0xfe, 0x31, 0x07, 0x14, 0x39, 0xb5,
	0x87, 0xc5, 0xe4, 0xab, 0xff, 0x06, 0xf7, 0x46, 0xd3, 0xf3, 0xa3, 0x99, 0x86, 0xa3, 0xa1, 0xf3,
	0xd1, 0xb1, 0x87, 0x60, 0x54, 0xcb, 0x07, 0xf8, 0xaf, 0x4e, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x34, 0xfc, 0xdb, 0x17, 0x7c, 0x03, 0x00, 0x00,
}
