path_root = "/home/yhao/git/work"
path_result = path_root + "/script/2019-dependency/con"
path_default_json = path_root + "/script/2019-dependency/con/default.json"

# linux_bc_dir = "/home/yuh/data/benchmark/linux/16-linux-clang-np"
path_linux_bc = "/home/yhao/benchmark/linux/16-linux-clang-np-bc-f"
path_taint = path_root + "/script/2019-dependency/taint_info"

dev = {
    "dev_ashmem": {
        "enable_syscalls": [
            "openat$ashmem",
            "ioctl$ASHMEM_SET_NAME",
            "ioctl$ASHMEM_GET_NAME",
            "ioctl$ASHMEM_SET_SIZE",
            "ioctl$ASHMEM_GET_SIZE",
            "ioctl$ASHMEM_SET_PROT_MASK",
            "ioctl$ASHMEM_GET_PROT_MASK",
            "ioctl$ASHMEM_GET_PIN_STATUS",
            "ioctl$ASHMEM_PURGE_ALL_CACHES",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_binder": {
        "enable_syscalls": [
            "syz_open_dev$binder",
            "mmap$binder",
            "ioctl$BINDER_SET_MAX_THREADS",
            "ioctl$BINDER_SET_CONTEXT_MGR",
            "ioctl$BINDER_THREAD_EXIT",
            "ioctl$BINDER_GET_NODE_DEBUG_INFO",
            "ioctl$BINDER_WRITE_READ",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_block": {
        "enable_syscalls": [
            "openat$nullb",
            "openat$md",
            "ioctl$BLKTRACESETUP",
            "ioctl$BLKTRACESTART",
            "ioctl$BLKTRACESTOP",
            "ioctl$BLKTRACETEARDOWN",
            "ioctl$BLKFLSBUF",
            "ioctl$BLKROSET",
            "ioctl$BLKDISCARD",
            "ioctl$BLKSECDISCARD",
            "ioctl$BLKZEROOUT",
            "ioctl$BLKREPORTZONE",
            "ioctl$BLKRESETZONE",
            "ioctl$BLKRAGET",
            "ioctl$BLKROGET",
            "ioctl$BLKBSZGET",
            "ioctl$BLKPBSZGET",
            "ioctl$BLKIOMIN",
            "ioctl$BLKIOOPT",
            "ioctl$BLKALIGNOFF",
            "ioctl$BLKSECTGET",
            "ioctl$BLKROTATIONAL",
            "ioctl$BLKFRASET",
            "ioctl$BLKBSZSET",
            "ioctl$BLKPG",
            "ioctl$BLKRRPART",
            "ioctl$BLKGETSIZE",
            "ioctl$BLKGETSIZE64",
            "ioctl$HDIO_GETGEO",
            "ioctl$IOC_PR_REGISTER",
            "ioctl$IOC_PR_RESERVE",
            "ioctl$IOC_PR_RELEASE",
            "ioctl$IOC_PR_PREEMPT",
            "ioctl$IOC_PR_PREEMPT_ABORT",
            "ioctl$IOC_PR_CLEAR",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_cdrom": {
        "enable_syscalls": [
            "syz_open_dev$CDROM_DEV_LINK",
            "ioctl$CDROMPAUSE",
            "ioctl$CDROMRESUME",
            "ioctl$CDROMPLAYMSF",
            "ioctl$CDROMPLAYTRKIND",
            "ioctl$CDROMREADTOCHDR",
            "ioctl$CDROMREADTOCENTRY",
            "ioctl$CDROMSTOP",
            "ioctl$CDROMSTART",
            "ioctl$CDROMEJECT",
            "ioctl$CDROMVOLCTRL",
            "ioctl$CDROMSUBCHNL",
            "ioctl$CDROMREADMODE2",
            "ioctl$CDROMREADMODE1",
            "ioctl$CDROMREADAUDIO",
            "ioctl$CDROMEJECT_SW",
            "ioctl$CDROMMULTISESSION",
            "ioctl$CDROM_GET_MCN",
            "ioctl$CDROMRESET",
            "ioctl$CDROMVOLREAD",
            "ioctl$CDROMREADRAW",
            "ioctl$CDROMREADCOOKED",
            "ioctl$CDROMSEEK",
            "ioctl$CDROMPLAYBLK",
            "ioctl$CDROMREADALL",
            "ioctl$CDROMGETSPINDOWN",
            "ioctl$CDROMSETSPINDOWN",
            "ioctl$CDROMCLOSETRAY",
            "ioctl$CDROM_SET_OPTIONS",
            "ioctl$CDROM_CLEAR_OPTIONS",
            "ioctl$CDROM_SELECT_SPEED",
            "ioctl$CDROM_SELECT_DISK",
            "ioctl$CDROM_MEDIA_CHANGED",
            "ioctl$CDROM_DISC_STATUS",
            "ioctl$CDROM_CHANGER_NSLOTS",
            "ioctl$CDROM_LOCKDOOR",
            "ioctl$CDROM_DEBUG",
            "ioctl$CDROM_GET_CAPABILITY",
            "ioctl$CDROMAUDIOBUFSIZ",
            "ioctl$DVD_READ_STRUCT",
            "ioctl$DVD_WRITE_STRUCT",
            "ioctl$DVD_AUTH",
            "ioctl$CDROM_SEND_PACKET",
            "ioctl$CDROM_NEXT_WRITABLE",
            "ioctl$CDROM_LAST_WRITTEN",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_dri": {
        "enable_syscalls": [
            "syz_open_dev$dri",
            "syz_open_dev$dricontrol",
            "syz_open_dev$drirender",
            "ioctl$DRM_IOCTL_VERSION",
            "ioctl$DRM_IOCTL_GET_UNIQUE",
            "ioctl$DRM_IOCTL_GET_MAGIC",
            "ioctl$DRM_IOCTL_IRQ_BUSID",
            "ioctl$DRM_IOCTL_GET_MAP",
            "ioctl$DRM_IOCTL_GET_CLIENT",
            "ioctl$DRM_IOCTL_GET_STATS",
            "ioctl$DRM_IOCTL_GET_CAP",
            "ioctl$DRM_IOCTL_SET_CLIENT_CAP",
            "ioctl$DRM_IOCTL_SET_VERSION",
            "ioctl$DRM_IOCTL_SET_UNIQUE",
            "ioctl$DRM_IOCTL_AUTH_MAGIC",
            "ioctl$DRM_IOCTL_ADD_MAP",
            "ioctl$DRM_IOCTL_RM_MAP",
            "ioctl$DRM_IOCTL_SET_SAREA_CTX",
            "ioctl$DRM_IOCTL_GET_SAREA_CTX",
            "ioctl$DRM_IOCTL_SET_MASTER",
            "ioctl$DRM_IOCTL_DROP_MASTER",
            "ioctl$DRM_IOCTL_ADD_CTX",
            "ioctl$DRM_IOCTL_RM_CTX",
            "ioctl$DRM_IOCTL_GET_CTX",
            "ioctl$DRM_IOCTL_SWITCH_CTX",
            "ioctl$DRM_IOCTL_NEW_CTX",
            "ioctl$DRM_IOCTL_RES_CTX",
            "ioctl$DRM_IOCTL_LOCK",
            "ioctl$DRM_IOCTL_UNLOCK",
            "ioctl$DRM_IOCTL_ADD_BUFS",
            "ioctl$DRM_IOCTL_MARK_BUFS",
            "ioctl$DRM_IOCTL_INFO_BUFS",
            "ioctl$DRM_IOCTL_MAP_BUFS",
            "ioctl$DRM_IOCTL_FREE_BUFS",
            "ioctl$DRM_IOCTL_DMA",
            "ioctl$DRM_IOCTL_CONTROL",
            "ioctl$DRM_IOCTL_AGP_ACQUIRE",
            "ioctl$DRM_IOCTL_AGP_RELEASE",
            "ioctl$DRM_IOCTL_AGP_ENABLE",
            "ioctl$DRM_IOCTL_AGP_INFO",
            "ioctl$DRM_IOCTL_AGP_ALLOC",
            "ioctl$DRM_IOCTL_AGP_FREE",
            "ioctl$DRM_IOCTL_AGP_BIND",
            "ioctl$DRM_IOCTL_AGP_UNBIND",
            "ioctl$DRM_IOCTL_SG_ALLOC",
            "ioctl$DRM_IOCTL_SG_FREE",
            "ioctl$DRM_IOCTL_WAIT_VBLANK",
            "ioctl$DRM_IOCTL_MODESET_CTL",
            "ioctl$DRM_IOCTL_GEM_OPEN",
            "ioctl$DRM_IOCTL_GEM_CLOSE",
            "ioctl$DRM_IOCTL_GEM_FLINK",
            "ioctl$DRM_IOCTL_MODE_GETRESOURCES",
            "ioctl$DRM_IOCTL_PRIME_HANDLE_TO_FD",
            "ioctl$DRM_IOCTL_PRIME_FD_TO_HANDLE",
            "ioctl$DRM_IOCTL_MODE_GETPLANERESOURCES",
            "ioctl$DRM_IOCTL_MODE_GETCRTC",
            "ioctl$DRM_IOCTL_MODE_SETCRTC",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_floppy": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_i2c": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_input": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_ion": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_loop": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_kvm": {
        "enable_syscalls": [
            "openat$kvm",
            "ioctl$KVM_CREATE_VM",
            "ioctl$KVM_GET_MSR_INDEX_LIST",
            "ioctl$KVM_CHECK_EXTENSION",
            "ioctl$KVM_GET_VCPU_MMAP_SIZE",
            "ioctl$KVM_GET_SUPPORTED_CPUID",
            "ioctl$KVM_GET_EMULATED_CPUID",
            "ioctl$KVM_X86_GET_MCE_CAP_SUPPORTED",
            "ioctl$KVM_GET_API_VERSION",
            "ioctl$KVM_CREATE_VCPU",
            "ioctl$KVM_CHECK_EXTENSION_VM",
            "ioctl$KVM_GET_DIRTY_LOG",
            "ioctl$KVM_CREATE_IRQCHIP",
            "ioctl$KVM_IRQ_LINE",
            "ioctl$KVM_IRQ_LINE_STATUS",
            "ioctl$KVM_GET_IRQCHIP",
            "ioctl$KVM_SET_IRQCHIP",
            "ioctl$KVM_XEN_HVM_CONFIG",
            "ioctl$KVM_GET_CLOCK",
            "ioctl$KVM_SET_CLOCK",
            "ioctl$KVM_SET_USER_MEMORY_REGION",
            "ioctl$KVM_SET_TSS_ADDR",
            "ioctl$KVM_ENABLE_CAP",
            "ioctl$KVM_SET_IDENTITY_MAP_ADDR",
            "ioctl$KVM_SET_BOOT_CPU_ID",
            "ioctl$KVM_PPC_GET_PVINFO",
            "ioctl$KVM_ASSIGN_PCI_DEVICE",
            "ioctl$KVM_DEASSIGN_PCI_DEVICE",
            "ioctl$KVM_ASSIGN_DEV_IRQ",
            "ioctl$KVM_DEASSIGN_DEV_IRQ",
            "ioctl$KVM_SET_GSI_ROUTING",
            "ioctl$KVM_ASSIGN_SET_MSIX_NR",
            "ioctl$KVM_ASSIGN_SET_MSIX_ENTRY",
            "ioctl$KVM_IOEVENTFD",
            "ioctl$KVM_ASSIGN_SET_INTX_MASK",
            "ioctl$KVM_SIGNAL_MSI",
            "ioctl$KVM_CREATE_PIT2",
            "ioctl$KVM_GET_PIT",
            "ioctl$KVM_SET_PIT",
            "ioctl$KVM_GET_PIT2",
            "ioctl$KVM_SET_PIT2",
            "ioctl$KVM_PPC_GET_SMMU_INFO",
            "ioctl$KVM_IRQFD",
            "ioctl$KVM_PPC_ALLOCATE_HTAB",
            "ioctl$KVM_CREATE_DEVICE",
            "ioctl$KVM_REGISTER_COALESCED_MMIO",
            "ioctl$KVM_UNREGISTER_COALESCED_MMIO",
            "ioctl$KVM_SET_NR_MMU_PAGES",
            "ioctl$KVM_GET_NR_MMU_PAGES",
            "ioctl$KVM_REINJECT_CONTROL",
            "ioctl$KVM_HYPERV_EVENTFD",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_nbd": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_net_tun": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_ppp": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_ptmx": {
        "enable_syscalls": [
            "openat$ptmx",
            "syz_open_pts",
            "ioctl$TCGETS",
            "ioctl$TCSETS",
            "ioctl$TCSETSW",
            "ioctl$TCSETSF",
            "ioctl$TCGETA",
            "ioctl$TCSETA",
            "ioctl$TCSETAW",
            "ioctl$TCSETAF",
            "ioctl$TIOCGLCKTRMIOS",
            "ioctl$TIOCSLCKTRMIOS",
            "ioctl$TIOCGWINSZ",
            "ioctl$TIOCSWINSZ",
            "ioctl$TCSBRK",
            "ioctl$TCSBRKP",
            "ioctl$TIOCSBRK",
            "ioctl$TIOCCBRK",
            "ioctl$TCXONC",
            "ioctl$FIONREAD",
            "ioctl$TIOCOUTQ",
            "ioctl$TCFLSH",
            "ioctl$TIOCSTI",
            "ioctl$TIOCCONS",
            "ioctl$TIOCSCTTY",
            "ioctl$TIOCNOTTY",
            "ioctl$TIOCGPGRP",
            "ioctl$TIOCSPGRP",
            "ioctl$TIOCGSID",
            "ioctl$TIOCEXCL",
            "ioctl$TIOCNXCL",
            "ioctl$TIOCGETD",
            "ioctl$TIOCSETD",
            "ioctl$TIOCPKT",
            "ioctl$TIOCMGET",
            "ioctl$TIOCMSET",
            "ioctl$TIOCMBIC",
            "ioctl$TIOCMBIS",
            "ioctl$TIOCGSOFTCAR",
            "ioctl$TIOCSSOFTCAR",
            "ioctl$KDGETLED",
            "ioctl$KDSETLED",
            "ioctl$KDGKBLED",
            "ioctl$KDSKBLED",
            "ioctl$KDGKBTYPE",
            "ioctl$KDADDIO",
            "ioctl$KDDELIO",
            "ioctl$KDENABIO",
            "ioctl$KDDISABIO",
            "ioctl$KDSETMODE",
            "ioctl$KDGETMODE",
            "ioctl$KDMKTONE",
            "ioctl$KIOCSOUND",
            "ioctl$GIO_CMAP",
            "ioctl$PIO_CMAP",
            "ioctl$GIO_FONT",
            "ioctl$GIO_FONTX",
            "ioctl$PIO_FONT",
            "ioctl$PIO_FONTX",
            "ioctl$PIO_FONTRESET",
            "ioctl$GIO_SCRNMAP",
            "ioctl$GIO_UNISCRNMAP",
            "ioctl$PIO_SCRNMAP",
            "ioctl$PIO_UNISCRNMAP",
            "ioctl$GIO_UNIMAP",
            "ioctl$PIO_UNIMAP",
            "ioctl$PIO_UNIMAPCLR",
            "ioctl$KDGKBMODE",
            "ioctl$KDSKBMODE",
            "ioctl$KDGKBMETA",
            "ioctl$KDSKBMETA",
            "ioctl$KDGKBENT",
            "ioctl$KDGKBSENT",
            "ioctl$KDSKBSENT",
            "ioctl$KDGKBDIACR",
            "ioctl$KDGETKEYCODE",
            "ioctl$KDSETKEYCODE",
            "ioctl$KDSIGACCEPT",
            "ioctl$VT_OPENQRY",
            "ioctl$VT_GETMODE",
            "ioctl$VT_SETMODE",
            "ioctl$VT_GETSTATE",
            "ioctl$VT_RELDISP",
            "ioctl$VT_ACTIVATE",
            "ioctl$VT_WAITACTIVE",
            "ioctl$VT_DISALLOCATE",
            "ioctl$VT_RESIZE",
            "ioctl$VT_RESIZEX",
            "ioctl$TIOCLINUX2",
            "ioctl$TIOCLINUX3",
            "ioctl$TIOCLINUX4",
            "ioctl$TIOCLINUX5",
            "ioctl$TIOCLINUX6",
            "ioctl$TIOCLINUX7",
            "ioctl$TIOCGSERIAL",
            "ioctl$TIOCSSERIAL",
            "ioctl$TCGETS2",
            "ioctl$TCSETS2",
            "ioctl$TIOCSERGETLSR",
            "ioctl$TIOCGRS485",
            "ioctl$TIOCSRS485",
            "ioctl$TIOCGISO7816",
            "ioctl$TIOCSISO7816",
            "ioctl$TIOCSPTLCK",
            "ioctl$TIOCGPTLCK",
            "ioctl$TIOCGPKT",
            "ioctl$TIOCSIG",
            "ioctl$TIOCVHANGUP",
            "ioctl$TIOCGDEV",
            "ioctl$TCGETX",
            "ioctl$TCSETX",
            "ioctl$TCSETXF",
            "ioctl$TCSETXW",
            "ioctl$TIOCMIWAIT",
            "ioctl$TIOCGICOUNT",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_random": {
        "enable_syscalls": [
            "openat$random",
            "openat$urandom",
            "ioctl$RNDGETENTCNT",
            "ioctl$RNDADDTOENTCNT",
            "ioctl$RNDADDENTROPY",
            "ioctl$RNDZAPENTCNT",
            "ioctl$RNDCLEARPOOL",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_rfkill": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_rtc": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_sg": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_snd_control": {
        "enable_syscalls": [

        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_snd_seq": {
        "enable_syscalls": [

            "syz_open_dev$sndseq",
            "write$sndseq",
            "ioctl$SNDRV_SEQ_IOCTL_PVERSION",
            "ioctl$SNDRV_SEQ_IOCTL_CLIENT_ID",
            "ioctl$SNDRV_SEQ_IOCTL_SYSTEM_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_RUNNING_MODE",
            "ioctl$SNDRV_SEQ_IOCTL_GET_CLIENT_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_SET_CLIENT_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_CREATE_PORT",
            "ioctl$SNDRV_SEQ_IOCTL_DELETE_PORT",
            "ioctl$SNDRV_SEQ_IOCTL_GET_PORT_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_SET_PORT_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_SUBSCRIBE_PORT",
            "ioctl$SNDRV_SEQ_IOCTL_UNSUBSCRIBE_PORT",
            "ioctl$SNDRV_SEQ_IOCTL_CREATE_QUEUE",
            "ioctl$SNDRV_SEQ_IOCTL_DELETE_QUEUE",
            "ioctl$SNDRV_SEQ_IOCTL_GET_QUEUE_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_SET_QUEUE_INFO",
            "ioctl$SNDRV_SEQ_IOCTL_GET_NAMED_QUEUE",
            "ioctl$SNDRV_SEQ_IOCTL_GET_QUEUE_STATUS",
            "ioctl$SNDRV_SEQ_IOCTL_GET_QUEUE_TEMPO",
            "ioctl$SNDRV_SEQ_IOCTL_SET_QUEUE_TEMPO",
            "ioctl$SNDRV_SEQ_IOCTL_GET_QUEUE_TIMER",
            "ioctl$SNDRV_SEQ_IOCTL_SET_QUEUE_TIMER",
            "ioctl$SNDRV_SEQ_IOCTL_GET_QUEUE_CLIENT",
            "ioctl$SNDRV_SEQ_IOCTL_SET_QUEUE_CLIENT",
            "ioctl$SNDRV_SEQ_IOCTL_GET_CLIENT_POOL",
            "ioctl$SNDRV_SEQ_IOCTL_SET_CLIENT_POOL",
            "ioctl$SNDRV_SEQ_IOCTL_REMOVE_EVENTS",
            "ioctl$SNDRV_SEQ_IOCTL_QUERY_SUBS",
            "ioctl$SNDRV_SEQ_IOCTL_GET_SUBSCRIPTION",
            "ioctl$SNDRV_SEQ_IOCTL_QUERY_NEXT_CLIENT",
            "ioctl$SNDRV_SEQ_IOCTL_QUERY_NEXT_PORT",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_snd_timer": {
        "enable_syscalls": [
            "syz_open_dev$sndtimer",
            "ioctl$SNDRV_TIMER_IOCTL_PVERSION",
            "ioctl$SNDRV_TIMER_IOCTL_NEXT_DEVICE",
            "ioctl$SNDRV_TIMER_IOCTL_TREAD",
            "ioctl$SNDRV_TIMER_IOCTL_GINFO",
            "ioctl$SNDRV_TIMER_IOCTL_GPARAMS",
            "ioctl$SNDRV_TIMER_IOCTL_GSTATUS",
            "ioctl$SNDRV_TIMER_IOCTL_SELECT",
            "ioctl$SNDRV_TIMER_IOCTL_INFO",
            "ioctl$SNDRV_TIMER_IOCTL_PARAMS",
            "ioctl$SNDRV_TIMER_IOCTL_STATUS",
            "ioctl$SNDRV_TIMER_IOCTL_START",
            "ioctl$SNDRV_TIMER_IOCTL_STOP",
            "ioctl$SNDRV_TIMER_IOCTL_CONTINUE",
            "ioctl$SNDRV_TIMER_IOCTL_PAUSE",
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_sr": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_uhid": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_uinput": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_userio": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
    "dev_video4linux": {
        "enable_syscalls": [
        ],
        "file_bc": path_linux_bc + "/arch/x86/kvm/built-in.bc",
        "path_s": [
            path_linux_bc + "/virt/kvm",
            path_linux_bc + "/arch/x86/kvm",
        ],
        "file_taint": path_taint + "/taint_info_kvm_dev_ioctl_serialize",
    },
}
